// Mocks generated by Mockito 5.4.6 from annotations
// in sociaanet/test/unit/usecases/auth_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sociaanet/features/auth/data/datasources/auth_datasource.dart'
    as _i3;
import 'package:sociaanet/features/auth/data/model/auth_api_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignupResponseModel_0 extends _i1.SmartFake
    implements _i2.SignupResponseModel {
  _FakeSignupResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponseModel_1 extends _i1.SmartFake
    implements _i2.LoginResponseModel {
  _FakeLoginResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValidateSessionResponseModel_2 extends _i1.SmartFake
    implements _i2.ValidateSessionResponseModel {
  _FakeValidateSessionResponseModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeGetUserInfoResponseModel_3 extends _i1.SmartFake
    implements _i2.GetUserInfoResponseModel {
  _FakeGetUserInfoResponseModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasource extends _i1.Mock
    implements _i3.AuthRemoteDatasource {
  @override
  _i4.Future<_i2.SignupResponseModel> signup(_i2.SignupRequestModel? request) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [request]),
            returnValue: _i4.Future<_i2.SignupResponseModel>.value(
              _FakeSignupResponseModel_0(
                this,
                Invocation.method(#signup, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.SignupResponseModel>.value(
                  _FakeSignupResponseModel_0(
                    this,
                    Invocation.method(#signup, [request]),
                  ),
                ),
          )
          as _i4.Future<_i2.SignupResponseModel>);

  @override
  _i4.Future<_i2.LoginResponseModel> login(_i2.LoginRequestModel? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i4.Future<_i2.LoginResponseModel>.value(
              _FakeLoginResponseModel_1(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.LoginResponseModel>.value(
              _FakeLoginResponseModel_1(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.LoginResponseModel>);

  @override
  _i4.Future<_i2.ValidateSessionResponseModel> validateSession(
    String? sessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateSession, [sessionId]),
            returnValue: _i4.Future<_i2.ValidateSessionResponseModel>.value(
              _FakeValidateSessionResponseModel_2(
                this,
                Invocation.method(#validateSession, [sessionId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.ValidateSessionResponseModel>.value(
                  _FakeValidateSessionResponseModel_2(
                    this,
                    Invocation.method(#validateSession, [sessionId]),
                  ),
                ),
          )
          as _i4.Future<_i2.ValidateSessionResponseModel>);

  @override
  _i4.Future<_i2.GetUserInfoResponseModel> getUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getUserInfo, []),
            returnValue: _i4.Future<_i2.GetUserInfoResponseModel>.value(
              _FakeGetUserInfoResponseModel_3(
                this,
                Invocation.method(#getUserInfo, []),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.GetUserInfoResponseModel>.value(
                  _FakeGetUserInfoResponseModel_3(
                    this,
                    Invocation.method(#getUserInfo, []),
                  ),
                ),
          )
          as _i4.Future<_i2.GetUserInfoResponseModel>);

  @override
  _i4.Future<void> forgotPasswordOtp(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPasswordOtp, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> changePasswordWithOtp({
    required String? email,
    required String? otp,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePasswordWithOtp, [], {
              #email: email,
              #otp: otp,
              #newPassword: newPassword,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
