// Mocks generated by Mockito 5.4.6 from annotations
// in sociaanet/test/unit/usecases/feed_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sociaanet/features/feed/data/datasources/feed_datasource.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FeedRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedRemoteDatasource extends _i1.Mock
    implements _i2.FeedRemoteDatasource {
  @override
  _i3.Future<Map<String, dynamic>> getHomeFeed({int? page, int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getHomeFeed, [], {#page: page, #limit: limit}),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getExploreFeed({int? page, int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getExploreFeed, [], {
              #page: page,
              #limit: limit,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getReelsFeed({int? page, int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getReelsFeed, [], {#page: page, #limit: limit}),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getSuggestedUsers({int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedUsers, [], {#limit: limit}),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
