// Mocks generated by Mockito 5.4.6 from annotations
// in sociaanet/test/unit/usecases/story_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sociaanet/features/story/data/datasources/story_datasource.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StoryDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoryDatasource extends _i1.Mock implements _i2.StoryDatasource {
  @override
  _i3.Future<List<dynamic>> getStories() =>
      (super.noSuchMethod(
            Invocation.method(#getStories, []),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
            returnValueForMissingStub: _i3.Future<List<dynamic>>.value(
              <dynamic>[],
            ),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<dynamic> createStory(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createStory, [data]),
            returnValue: _i3.Future<dynamic>.value(),
            returnValueForMissingStub: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<void> viewStory(String? storyId) =>
      (super.noSuchMethod(
            Invocation.method(#viewStory, [storyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
