// Mocks generated by Mockito 5.4.6 from annotations
// in sociaanet/test/unit/usecases/user_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sociaanet/features/auth/data/model/auth_api_model.dart' as _i2;
import 'package:sociaanet/features/user/data/datasources/user_datasource.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetUserInfoResponseModel_0 extends _i1.SmartFake
    implements _i2.GetUserInfoResponseModel {
  _FakeGetUserInfoResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataSource extends _i1.Mock implements _i3.UserDataSource {
  @override
  _i4.Future<_i2.GetUserInfoResponseModel> uploadAvatar(_i5.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAvatar, [imageFile]),
            returnValue: _i4.Future<_i2.GetUserInfoResponseModel>.value(
              _FakeGetUserInfoResponseModel_0(
                this,
                Invocation.method(#uploadAvatar, [imageFile]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.GetUserInfoResponseModel>.value(
                  _FakeGetUserInfoResponseModel_0(
                    this,
                    Invocation.method(#uploadAvatar, [imageFile]),
                  ),
                ),
          )
          as _i4.Future<_i2.GetUserInfoResponseModel>);

  @override
  _i4.Future<_i2.GetUserInfoResponseModel> getUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getUserInfo, []),
            returnValue: _i4.Future<_i2.GetUserInfoResponseModel>.value(
              _FakeGetUserInfoResponseModel_0(
                this,
                Invocation.method(#getUserInfo, []),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.GetUserInfoResponseModel>.value(
                  _FakeGetUserInfoResponseModel_0(
                    this,
                    Invocation.method(#getUserInfo, []),
                  ),
                ),
          )
          as _i4.Future<_i2.GetUserInfoResponseModel>);

  @override
  _i4.Future<Map<String, dynamic>> getUserProfile(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [username]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> updateBio(String? bio) =>
      (super.noSuchMethod(
            Invocation.method(#updateBio, [bio]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#updateUsername, [username]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateFullname(String? fullName) =>
      (super.noSuchMethod(
            Invocation.method(#updateFullname, [fullName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> searchUsers(
    String? query, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchUsers,
              [query],
              {#page: page, #limit: limit},
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> followUser(String? followeeId) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [followeeId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> unfollowUser(String? followeeId) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [followeeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getFollowers(
    String? userId, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFollowers,
              [userId],
              {#page: page, #limit: limit},
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getFollowing(
    String? userId, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFollowing,
              [userId],
              {#page: page, #limit: limit},
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getActivities({
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActivities, [], {#page: page, #limit: limit}),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getSavedItems({
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedItems, [], {#page: page, #limit: limit}),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}
