// Mocks generated by Mockito 5.4.6 from annotations
// in sociaanet/test/unit/viewmodels/auth_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sociaanet/core/error/failures.dart' as _i5;
import 'package:sociaanet/core/services/hive/hive_service.dart' as _i7;
import 'package:sociaanet/features/auth/data/model/auth_api_model.dart' as _i6;
import 'package:sociaanet/features/auth/data/repositories/auth_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepositoryImpl extends _i1.Mock
    implements _i3.AuthRepositoryImpl {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SignupResponseModel>> signup({
    required String? fullName,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [], {
              #fullName: fullName,
              #email: email,
              #password: password,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.SignupResponseModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.SignupResponseModel>(
                    this,
                    Invocation.method(#signup, [], {
                      #fullName: fullName,
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.SignupResponseModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.SignupResponseModel>(
                    this,
                    Invocation.method(#signup, [], {
                      #fullName: fullName,
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.SignupResponseModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.LoginResponseModel>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.LoginResponseModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.LoginResponseModel>(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.LoginResponseModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.LoginResponseModel>(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.LoginResponseModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ValidateSessionResponseModel>>
  validateSession({required String? sessionId}) =>
      (super.noSuchMethod(
            Invocation.method(#validateSession, [], {#sessionId: sessionId}),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.ValidateSessionResponseModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.ValidateSessionResponseModel>(
                    this,
                    Invocation.method(#validateSession, [], {
                      #sessionId: sessionId,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.ValidateSessionResponseModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.ValidateSessionResponseModel>(
                    this,
                    Invocation.method(#validateSession, [], {
                      #sessionId: sessionId,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.Failure, _i6.ValidateSessionResponseModel>
          >);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.GetUserInfoResponseModel>>
  getUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getUserInfo, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.GetUserInfoResponseModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.GetUserInfoResponseModel>(
                    this,
                    Invocation.method(#getUserInfo, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.GetUserInfoResponseModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.GetUserInfoResponseModel>(
                    this,
                    Invocation.method(#getUserInfo, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.GetUserInfoResponseModel>>);
}

/// A class which mocks [HiveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveService extends _i1.Mock implements _i7.HiveService {
  @override
  _i4.Future<void> saveSessionId(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#saveSessionId, [sessionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool hasSession() =>
      (super.noSuchMethod(
            Invocation.method(#hasSession, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> deleteSessionId() =>
      (super.noSuchMethod(
            Invocation.method(#deleteSessionId, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserId, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUserId() =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserId, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setLoggedIn(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setLoggedIn, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> clearAuthData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
