// Mocks generated by Mockito 5.4.6 from annotations
// in sociaanet/test/unit/viewmodels/chat_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sociaanet/core/error/failures.dart' as _i5;
import 'package:sociaanet/core/models/models.dart' as _i6;
import 'package:sociaanet/features/chat/data/repositories/chat_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepositoryImpl extends _i1.Mock
    implements _i3.ChatRepositoryImpl {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ChatConversation>>>
  getConversations({int? page = 1, int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, [], {
              #page: page,
              #limit: limit,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ChatConversation>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ChatConversation>>(
                    this,
                    Invocation.method(#getConversations, [], {
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ChatConversation>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ChatConversation>>(
                    this,
                    Invocation.method(#getConversations, [], {
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ChatConversation>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ChatConversation>>
  getOrCreateDirectConversation(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateDirectConversation, [userId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ChatConversation>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ChatConversation>(
                    this,
                    Invocation.method(#getOrCreateDirectConversation, [userId]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ChatConversation>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ChatConversation>(
                    this,
                    Invocation.method(#getOrCreateDirectConversation, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ChatConversation>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ChatConversation>>
  createGroupConversation({
    required String? name,
    required List<String>? participantIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGroupConversation, [], {
              #name: name,
              #participantIds: participantIds,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ChatConversation>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ChatConversation>(
                    this,
                    Invocation.method(#createGroupConversation, [], {
                      #name: name,
                      #participantIds: participantIds,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ChatConversation>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ChatConversation>(
                    this,
                    Invocation.method(#createGroupConversation, [], {
                      #name: name,
                      #participantIds: participantIds,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ChatConversation>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ChatConversation>> getConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversation, [conversationId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ChatConversation>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ChatConversation>(
                    this,
                    Invocation.method(#getConversation, [conversationId]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ChatConversation>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ChatConversation>(
                    this,
                    Invocation.method(#getConversation, [conversationId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ChatConversation>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ChatMessage>>> getMessages(
    String? conversationId, {
    int? page = 1,
    int? limit = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMessages,
              [conversationId],
              {#page: page, #limit: limit},
            ),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ChatMessage>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ChatMessage>>(
                    this,
                    Invocation.method(
                      #getMessages,
                      [conversationId],
                      {#page: page, #limit: limit},
                    ),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ChatMessage>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ChatMessage>>(
                    this,
                    Invocation.method(
                      #getMessages,
                      [conversationId],
                      {#page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ChatMessage>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ChatMessage>> sendMessage({
    required String? conversationId,
    required String? content,
    String? messageType = 'text',
    List<String>? mediaKeys,
    String? replyToId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #conversationId: conversationId,
              #content: content,
              #messageType: messageType,
              #mediaKeys: mediaKeys,
              #replyToId: replyToId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ChatMessage>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ChatMessage>(
                    this,
                    Invocation.method(#sendMessage, [], {
                      #conversationId: conversationId,
                      #content: content,
                      #messageType: messageType,
                      #mediaKeys: mediaKeys,
                      #replyToId: replyToId,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ChatMessage>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ChatMessage>(
                    this,
                    Invocation.method(#sendMessage, [], {
                      #conversationId: conversationId,
                      #content: content,
                      #messageType: messageType,
                      #mediaKeys: mediaKeys,
                      #replyToId: replyToId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ChatMessage>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> markAsRead(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [conversationId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#markAsRead, [conversationId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#markAsRead, [conversationId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> reactToMessage(
    String? messageId,
    String? emoji,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reactToMessage, [messageId, emoji]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#reactToMessage, [messageId, emoji]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#reactToMessage, [messageId, emoji]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeReaction(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#removeReaction, [messageId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#removeReaction, [messageId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#removeReaction, [messageId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteMessage, [messageId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#deleteMessage, [messageId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [conversationId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteConversation, [conversationId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#deleteConversation, [conversationId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getTotalUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalUnreadCount, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
              _FakeEither_0<_i5.Failure, int>(
                this,
                Invocation.method(#getTotalUnreadCount, []),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, int>>.value(
                  _FakeEither_0<_i5.Failure, int>(
                    this,
                    Invocation.method(#getTotalUnreadCount, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
  getFriends() =>
      (super.noSuchMethod(
            Invocation.method(#getFriends, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<Map<String, dynamic>>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#getFriends, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<Map<String, dynamic>>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#getFriends, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
  getMessageRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getMessageRequests, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#getMessageRequests, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#getMessageRequests, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getMessageRequestsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getMessageRequestsCount, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
              _FakeEither_0<_i5.Failure, int>(
                this,
                Invocation.method(#getMessageRequestsCount, []),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, int>>.value(
                  _FakeEither_0<_i5.Failure, int>(
                    this,
                    Invocation.method(#getMessageRequestsCount, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> acceptMessageRequest(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#acceptMessageRequest, [conversationId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#acceptMessageRequest, [conversationId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#acceptMessageRequest, [conversationId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> rejectMessageRequest(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rejectMessageRequest, [conversationId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#rejectMessageRequest, [conversationId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#rejectMessageRequest, [conversationId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
