// Mocks generated by Mockito 5.4.6 from annotations
// in sociaanet/test/unit/viewmodels/post_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sociaanet/core/error/failures.dart' as _i5;
import 'package:sociaanet/core/models/post_model.dart' as _i6;
import 'package:sociaanet/features/post/data/repositories/post_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i3.PostRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Post>> createPost({
    required String? caption,
    required List<String>? imagePaths,
    String? visibility,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #caption: caption,
              #imagePaths: imagePaths,
              #visibility: visibility,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Post>>.value(
              _FakeEither_0<_i5.Failure, _i6.Post>(
                this,
                Invocation.method(#createPost, [], {
                  #caption: caption,
                  #imagePaths: imagePaths,
                  #visibility: visibility,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Post>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Post>(
                    this,
                    Invocation.method(#createPost, [], {
                      #caption: caption,
                      #imagePaths: imagePaths,
                      #visibility: visibility,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Post>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Post>> getPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [postId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Post>>.value(
              _FakeEither_0<_i5.Failure, _i6.Post>(
                this,
                Invocation.method(#getPost, [postId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Post>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Post>(
                    this,
                    Invocation.method(#getPost, [postId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Post>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updatePostVisibility(
    String? postId,
    String? visibility,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePostVisibility, [postId, visibility]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updatePostVisibility, [postId, visibility]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#updatePostVisibility, [
                      postId,
                      visibility,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> recordView(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#recordView, [postId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#recordView, [postId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#recordView, [postId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> likePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#likePost, [postId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#likePost, [postId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#likePost, [postId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unlikePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#unlikePost, [postId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#unlikePost, [postId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#unlikePost, [postId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> repostPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#repostPost, [postId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#repostPost, [postId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#repostPost, [postId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unrepostPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#unrepostPost, [postId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#unrepostPost, [postId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#unrepostPost, [postId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> savePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#savePost, [postId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#savePost, [postId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#savePost, [postId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unsavePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#unsavePost, [postId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#unsavePost, [postId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#unsavePost, [postId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
