// Mocks generated by Mockito 5.4.6 from annotations
// in sociaanet/test/unit/viewmodels/settings_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sociaanet/core/error/failures.dart' as _i5;
import 'package:sociaanet/core/models/settings_model.dart' as _i6;
import 'package:sociaanet/features/settings/data/repositories/settings_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i3.SettingsRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserSettings>> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.UserSettings>>.value(
                  _FakeEither_0<_i5.Failure, _i6.UserSettings>(
                    this,
                    Invocation.method(#getSettings, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i6.UserSettings>>.value(
                  _FakeEither_0<_i5.Failure, _i6.UserSettings>(
                    this,
                    Invocation.method(#getSettings, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserSettings>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updatePrivacy(
    Map<String, dynamic>? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePrivacy, [settings]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updatePrivacy, [settings]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#updatePrivacy, [settings]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateNotifications(
    Map<String, dynamic>? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateNotifications, [settings]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateNotifications, [settings]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#updateNotifications, [settings]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateAppearance(
    Map<String, dynamic>? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppearance, [settings]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateAppearance, [settings]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#updateAppearance, [settings]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateFeed(
    Map<String, dynamic>? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateFeed, [settings]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateFeed, [settings]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#updateFeed, [settings]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#changePassword, [], {
                  #currentPassword: currentPassword,
                  #newPassword: newPassword,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#changePassword, [], {
                      #currentPassword: currentPassword,
                      #newPassword: newPassword,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
